development:
  adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") %>/<%= ENV.fetch("REDIS_DB") %>
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  url: "redis://localhost:6379/1"


test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:94fe2bfd88879a9a682b3e349fbdffc5@spinyfin.redistogo.com:11357/
  channel_prefix: Real_Estate_api_production
